module.exports = {
  USER_LOGIN: 'USERS/USER_LOGIN',
  USER_LOGIN_SUCCESS: 'USERS/USER_LOGIN_SUCCESS',
  USER_LOGIN_ERROR: 'USERS/USER_LOGIN_ERROR',
  UPDATE_USER_ID: 'USERS/UPDATE_USER_ID',
  LOGOUT_USER: 'USER/LOGOUT_USER',
  LOAD_USER: 'USER/LOAD_USER'
};
